root: true
env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  # project: './tsconfig.json'
  # tsconfigRootDir: './'
plugins:
  - '@typescript-eslint'
  - import
  - prettier
rules: {
  'import/order': [ 'error', {
    alphabetize: { order: 'asc', caseInsensitive: true },
    'newlines-between': 'always',
    groups: [ [ 'builtin', 'external', 'internal' ], [ 'index', 'sibling', 'parent', 'object' ], [ 'type' ] ] } ]
}
